### ISSUE TITLE
Config for translating messages

### ISSUE THREAD

**Issue by hilltty** [srnyx/personal-phantoms#2]
### What and How?

```
messages:
   no-permission: "&cYou do not have permission to use this command!"
   ivalid-player: "&4{player} &c is an invalid player!"
   must-be-player: "&cYou must be a player to use this command!"
   cooldown: "&cYou must wait &4 {timer}&c seconds before using this command again!"
   # and so is everyone else
```

### Why?

I think this would be incredibly handy, because now you need to recompile the plugin every time to change the messages.

### Are there alternatives?

Change the message in the source code and compile the plugin

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.
